# Generated by Django 4.2.4 on 2024-02-02 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0003_alter_discovery_date_alter_discovery_date_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 2, 14, 12, 33, 470340, tzinfo=datetime.timezone.utc), verbose_name='Год открытия'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='date_complete',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 14, 12, 33, 470340, tzinfo=datetime.timezone.utc), verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 14, 12, 33, 470340, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='date_of_formation',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 14, 12, 33, 470340, tzinfo=datetime.timezone.utc), verbose_name='Дата формирования'),
        ),
    ]
